name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install dependencies
        run: npm ci
      - name: Build the frontend app
        run: npm run build
      - name: Sync the bucket
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
