name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: deploy CDK app
        run: cdk deploy --require-approval never
        working-directory: ./infra
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          STATIC_SITE_BUCKET: ${{ secrets.STATIC_SITE_BUCKET }}
          REDIRECT_SITE_BUCKET: ${{ secrets.REDIRECT_SITE_BUCKET }}

      # redeploy frontend because the bucket might have been emptied
      - name: Install dependencies
        working-directory: ./front
        run: npm ci
      - name: Build the app
        working-directory: ./front
        run: npm run build
      - name: Sync the bucket
        working-directory: ./front
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
