name: Test Pull Request

on:
    pull_request:
        branches:
            - main

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci
            - name: Test formatting
              run: npm run lint:format
            - name: Test style linting
              run: npm run lint:style
            - name: Test code linding
              run: npm run lint:code
            - name: Test Astro
              run: npm run check
